### ISSUE TITLE
is the example data available? 

### ISSUE THREAD

**Issue by ethanbass** [xdomingoal/erah-devel#15]
Is the example data from the vignette publicly available somewhere? (I can't seem to locate it). If not, it would be helpful to have some example data so people can follow along with the vignette and actually run the examples to see the intended behavior of the package. I am trying to follow along with the vignette using my own data, but the deconvolution process is not returning any features. It's hard to figure out where the problem lies without a working example. Thanks.
Ethan

**Comment by xdomingoal** [comment]
please use the CRAN version, the Github's version is for developers only, as stated in the description. There are sample files available in Metabolights (see Section 2 of the CRAN's vignette).

**Comment by ethanbass** [comment]
OK, thanks
